### ISSUE TITLE
Dol Guldur - "Dominion of the Sorcerer"

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#539]
Dol Guldur's road to the "Dominion of the Sorcerer"

**Initial design of the event chain**
1. Subjugation of Fallen Men of Dol Guldur (dark aligned men in dejure Dol Guldur get events to submit). Unlocks subjugation CB in the area for those who do not kneel.
2. Subjugation of Fallen Men around Dol Guldur (dark aligned men in the Brownlands, Drownholt, and Central Mirkwood get events for submission). Subjugation CB unlocked for the area.
3. Assaults on the Elven-realms
4. Invasion of the Anduin Vale
5. Creation of Imperial Title
6. Optional subjugation of Gundabad

- [x] 1. Subjugation Decision - Evil woodmen - De Jure Dol Guldur
- [x] 1.5 Subjugation Decision - Evil neighbours - De Jure Brownlands/Angaladh
- [x] 2.1 Assault on Lasgalen - De Jure Lasgalen
- [x] 2.2 Assault on Lothlorien - De Jure Lothlorien
- [x] 3 Invasion of Anduin Vale - De Jure Anduin Vale
- [x] 4. Creation of "Dominion of the Sorcerer" - Empire Title
- [x] 5. Subjugate Gundabad/Anneithel

**Jamie-san Edit**

Also should consider whether it's worth having a minor decision to seek support from Mordor (à la #540).

- [ ] Consider support from seek Mordor minor decision

![dgarea](https://user-images.githubusercontent.com/12032489/214630397-3b957256-9c55-454f-bfe6-1aa6bcf25ffa.png)
![suggestiondolguldur](https://user-images.githubusercontent.com/12032489/214630405-6b372229-9452-49a8-90e7-db581be3dc6f.png)

**Comment by JukeJukestar** [comment]
I think this would work best if they arent Lidless Eye at game start, (Maybe just cynical)
They are then offered power by the Dark Forces of Dol Guldur, and can convert to Lidless Eye (Which the AI should usually do) and later swear fealty to Dol Guldur (Perhaps a modifier that increases same faith vassalization acceptance?)

The goal should be to do it in a way where they eventually swear fealty to Dol Guldur (even without player intervention), because otherwise the Dol Guldur AI will choose to just duchy conquer them, in which case they would be replaced by Orc Rulers

**Comment by jj248** [comment]
Moving this to 'In Progress' column as it is very much in progress!

**Comment by blackbird5598** [comment]
Don't know what exactly needed testing, however Decisions are all working & functional, although for some reason DG has the option to https://github.com/MattTheLegoman/RealmsInExile/issues/743. If theres a concern that Dol Guldur could get stomped on in a early mp war with Lothlorien I'd say just give them a truce & or protectorate status from Sauron that would expire in a couple years. A player could easily go defensive negotiations and ally themselves with Sauron if need be in a mp.

![image](https://user-images.githubusercontent.com/125709421/221476497-e1e87191-610c-45cb-bcf1-4fae65d8f632.png)"

but yeah DG definitely does need something in the early game so that a player lothlorien doesn't simply march on them & kill them.

**Comment by wFredsch** [comment]
@blackbird5598 everything needed testing. If its working, balancing, pacing of the decisions. Just everything 😀

**Comment by JukeJukestar** [comment]
I think a truce for a decade or so would be ideal - to represent the elves needing time to collect their forces before being able to launch a large scale assault on them

**Comment by Jauffr** [comment]
All the decisions work as intended with console commands. Balancing will of course require an actual playthrough to see for certain, however I think everything **looks** both balanced an fun to play.

I can not see any point in a truce for a decade or so. Lothlorien never actually attacks DG in the first place and would only be theoretically capable of doing so if they were bordering one another. Though she would never actually declare war to take land from him, due to not having Drownholt as either her dejure, claimed, or as an elven homeland. I would recommend quite the opposite of a truce. I think that Lothlorien's title holder should get claims on Drownholt if DG borders her/owns the Drownholt duchy capital c_thorlorien to give her a chance to attack if the situation seems to call for it. This will lead the gameplay to either the war of the ring canonical outcome where she defeats Khamul, or her being defeated and the Dominion of the Sorcerer being more likely

**Comment by RedArkady** [comment]
I agree that a truce is superfluous.

I'm not sure a claim is needed on Drownholt though, because don't the elves have a casus belli that they can use against evil realms? So if DG takes it then Lothlorien can push back. That's how it was all intended to work anyway, in line with the canonical outcome.

**Comment by Jauffr** [comment]
They have a CB they can use against evil realms, however they will not use it against DG, for the same reason they won't use it on the withered court. all that it does is give the land in question to a good version of the locals. This means that Galadriel has next to no motivation to use it on any evil faction next to her. In the current implementation, she will never seek to actually attack DG, only to defend herself and the fey court leofrings. If she was given claims on DG holding Drownholt, it would enable her to attack for that land and as a result be bordering the Amon Lanc duchy that we want her to attempt to take

**Comment by savagesach** [comment]
after reviewing dol guldur's military power, I suggest khamul be given some starting maa like galadriel and thranduil as a more permanent measure to ensure he doesn't get curbstomped
![image](https://user-images.githubusercontent.com/86676697/226802941-6623f661-1d22-4a56-b6ee-11e2b6231d1c.png)
![image](https://user-images.githubusercontent.com/86676697/226802973-7c47beec-0426-4836-ab18-41b3fe26d341.png)
![image](https://user-images.githubusercontent.com/86676697/226802995-eb8ca8e2-2c6e-4ecf-b783-e75c88d13f6d.png)

**Comment by Remerod** [comment]
hmm, that seems fitting

**Comment by savagesach** [comment]
okay after testing dol guldur, I can safely say dol guldur does not need any more buffs. I'm satisfied with how things currently are.

**Comment by savagesach** [comment]
sorry I almost forgot, there are issues with artifacts, the ulukai, mirror of galadriel, and woodland realm crown do not get added to khamuls artifact collection

**Comment by BriceLeduc** [comment]
this should be fixed

**Comment by savagesach** [comment]
if you look at these three decisions, both the lorien and the lasgalen desecration do not mention getting artifacts, unlike the anduin vale decision. The gundabad decision has the same issue. Also khamul can still see the destroy dol guldur decision if he holds the kingdom of lorien
![image](https://user-images.githubusercontent.com/86676697/232365897-1ba34d24-9c12-4955-a656-daffcafcbd4a.png)
![image](https://user-images.githubusercontent.com/86676697/232365923-cfbc4922-366d-4f23-89de-daad48851303.png)
![image](https://user-images.githubusercontent.com/86676697/232365944-fa095abd-c788-4467-90c8-b1b871c2899c.png)
![image](https://user-images.githubusercontent.com/86676697/232366884-a083bc84-c29f-46b2-9d15-43c43b99e3b9.png)
![image](https://user-images.githubusercontent.com/86676697/232366712-5153368d-c5f0-4c10-89e8-c2e08bec19e8.png)

**Comment by jj248** [comment]
Decision made not to implement last point.  Moving to testing for final opportunity for feedback.

**Comment by savagesach** [comment]
I played a dol guldur campaign and aside from the issues that have already been fixed or not implemented, everything works as intended. I think this issue can be closed.
